apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: externalsecrets.external-secrets.io
  labels:
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/part-of: external-secrets
spec:
  group: external-secrets.io
  names:
    kind: ExternalSecret
    listKind: ExternalSecretList
    plural: externalsecrets
    singular: externalsecret
  scope: Namespaced
  versions:
  - name: v1beta1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              refreshInterval:
                type: string
              secretStoreRef:
                type: object
                properties:
                  name:
                    type: string
                  kind:
                    type: string
              target:
                type: object
                properties:
                  name:
                    type: string
                  template:
                    type: object
                  creationPolicy:
                    type: string
              data:
                type: array
                items:
                  type: object
                  properties:
                    secretKey:
                      type: string
                    remoteRef:
                      type: object
                      properties:
                        key:
                          type: string
                        property:
                          type: string
              dataFrom:
                type: array
                items:
                  type: object
                  properties:
                    extract:
                      type: string
                    find:
                      type: string
    additionalPrinterColumns:
      - name: Age
        type: date
        jsonPath: .metadata.creationTimestamp
