apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: example-vault-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-secretstore
    kind: SecretStore
  target:
    name: secret-to-be-created
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: secret/data/demo
        property: username
    - secretKey: password
      remoteRef:
        key: secret/data/demo
        property: password
