apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: vault-secretstore
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"  # adresa ta Vault în cluster
      path: "secret"  # path-ul folosit în Vault, de obicei 'secret' sau 'secret/data' pentru KV v2
      version: "v2"  # dacă folosești KV versiunea 2 în Vault
      auth:
        token:
          secretRef:
            name: vault-token-secret
            key: token
