apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:Costel03/main.git'  # schimbă cu repo-ul tău
    targetRevision: HEAD
    path: ngnix  # directorul din repo unde sunt manifestele nginx
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
