name: Deploy Splunk App

on:
  workflow_dispatch:

jobs:
  build:
    name: Build App
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Alte comenzi de build pot fi adăugate aici, dacă e nevoie

  staging:
    name: Deploy to staging
    runs-on: self-hosted
    needs: build
    environment:
      name: staging
      url: ${{ steps.deploy_staging.outputs.webapp-url }}
    steps:
      - name: Step 1 - Mesaj personalizat pe branch
        run: |
          echo "Branch: ${{ github.ref_name }}"

          if [ "${{ github.ref_name }}" = "master" ]; then
            echo "Salut Costel"
          elif [ "${{ github.ref_name }}" = "dev" ]; then
            echo "Salut Adrian"
          else
            echo "Salut dintr-un alt branch: ${{ github.ref_name }}"
      
      # Exemplu de pas pentru deploy (trebuie adaptat după caz)
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          slot-name: staging
